# 默认开发环境配置
# 等同于 docker-compose.dev.yml
# 使用方式: docker-compose up

version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: carbon-emission-postgres-0527
    environment:
      POSTGRES_DB: carbon_emission_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - carbon-emission-network-0527
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: carbon-emission-redis-0527
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - carbon-emission-network-0527
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:


networks:
  carbon-emission-network-0527:
    driver: bridge
